name: Deploy to staging environment
on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

env:
  WEBSITE_URL: "https://hanyuone.live/staging/${{ github.head_ref }}"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # ==================== SETUP ====================
      # Install Rust
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown
      # Install Trunk and WASM for building webapp
      - uses: jetli/trunk-action@v0.5.0
      - uses: jetli/wasm-bindgen-action@v0.2.0
        with:
          version: '0.2.105'
      # Install Node and PNPM
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false
      # Checkout repo
      - uses: actions/checkout@v4
      # =================== INSTALL ===================
      # Cache Rust build files
      - uses: Swatinem/rust-cache@v2
      # PNPM caching and installing dependencies
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      # ==================== BUILD ====================
      - name: Add base URL
        shell: bash
        run: |
          ./scripts/write_index.sh "${{ env.WEBSITE_URL }}"
      - name: Build website
        run: pnpm build
      # ================== CHECKOUT ===================
      - name: Remove all other folders
        shell: bash
        run: |
          shopt -s extglob
          rm -rf !(dist)
      - name: Checkout gh-pages
        uses: actions/checkout@v6
        with:
          ref: gh-pages
          clean: false
      - name: Transfer dist folder to proper location
        run: |
          rm -rf staging/${{ github.head_ref }}
          mkdir -p staging/${{ github.head_ref }}
          mv dist/* staging/${{ github.head_ref }}
      - name: Upload to gh-pages branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "generated"
          git push
